govdata:
  baseurl: "https://www.govdata.de/ckan/api/3/action"
  whitelist:
    - "auswaertiges-amt"
    - "badv"
    - "bafa"
    - "bam"
    - "baua"
    - "bbsr"
    - "bmas"
    - "bmel"
    - "bmf"
    - "bmfsfj"
    - "bmi"
    - "bmvg"
    - "bmwi"
    - "bmz"
    - "bsa"
    - "bundesamt-fur-justiz"
    - "bundesministerium-fur-bildung-und-forschung"
    - "bva"
    - "bvl"
    - "bzst"
    - "dpma"
    - "itzbund"
    - "mcloud"
    - "mri"
    - "statistisches-bundesamt"
    - "zoll"